name: Upload Generated APKs and AAB

on:
  push:
    branches:
      - "release/**"
  workflow_dispatch:

env:
  main_project_module: app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Set Up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: "gradle"

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Run gradle tests
        run: ./gradlew test --no-daemon --stacktrace

      - name: Build gradle project
        run: ./gradlew build --no-daemon --stacktrace

      - name: Build apk debug project (APK)
        run: ./gradlew :${{ env.main_project_module }}:assembleDebug --no-daemon --stacktrace

      - name: Build apk release project (APK)
        run: ./gradlew :${{ env.main_project_module }}:assembleRelease --no-daemon --stacktrace

      - name: Build app bundle release (AAB)
        run: ./gradlew :${{ env.main_project_module }}:bundleRelease --no-daemon --stacktrace

      - name: Upload APK Debug
        uses: actions/upload-artifact@v4
        with:
          name: "APKs debug"
          path: ${{ env.main_project_module }}/build/outputs/apk/debug/

      - name: Upload APK Release
        uses: actions/upload-artifact@v4
        with:
          name: "APKs release"
          path: ${{ env.main_project_module }}/build/outputs/apk/release/

      - name: Upload AAB (App Bundle) Release
        uses: actions/upload-artifact@v4
        with:
          name: "AAB release"
          path: ${{ env.main_project_module }}/build/outputs/bundle/release/
